apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-token-auth
  namespace: local-devops
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-devops-secret-store
  target:
    name: local-devops-secret
  data:
    - secretKey: TEST_SECRET
      remoteRef:
        # Example path in your new KV secret engine
        key: kv/test/dev
        property: testSecret