apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-devops
resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
  - services.yaml
  - secret.yaml
configMapGenerator:
  - name: sample-backend-config
    files: 
      - config.properties